// pages/FinalReport.jsx
import "./FinalReport.css";

export default function FinalReport() {
  const data = JSON.parse(sessionStorage.getItem("aortix_result"));

  return (
    <div className="final-container">
      <div className="final-card">
        <h2 className="final-title">AI-Generated Clinical Summary</h2>

        <div className="chat-wrapper">
          <div className="chat-bubble">
            {data?.gen_ai_report || "Waiting for backend response..."}
          </div>
        </div>

        <div className="final-footer">
          Generated by AORTIX — Cardiovascular Digital Twin
        </div>
      </div>
    </div>
  );
}
